apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ostad-app
      version: blue
  template:
    metadata:
      labels:
        app: ostad-app
        version: blue
    spec:
      containers:
        - name: ostad-app
          image: ashraful90/ostad-app:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"