apiVersion: v1
kind: Service
metadata:
  name: ostad-app-service
spec:
  type: NodePort
  selector:
    app: ostad-app-service
    version: blue  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
