apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashrafulrcr43/Kubernets_Argocd_project
    targetRevision: HEAD
    path: .               # 👈 root folder
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
